# Generated by Django 4.1 on 2022-08-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kalima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kalima_text', models.CharField(max_length=200)),
                ('kalima_Fr', models.CharField(max_length=200)),
                ('kalima_En', models.CharField(max_length=200)),
                ('publishe_date', models.DateField(verbose_name='Date Published')),
            ],
        ),
    ]
