# Generated by Django 4.1 on 2022-09-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kalima',
            name='ar_decripetion',
            field=models.TextField(default='welcom'),
            preserve_default=False,
        ),
    ]
