# Generated by Django 4.1 on 2022-09-08 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0002_kalima_ar_decripetion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kalima',
            old_name='ar_decripetion',
            new_name='ar_description',
        ),
    ]
