# Generated by Django 4.1 on 2022-09-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0003_rename_ar_decripetion_kalima_ar_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='kalima',
            name='en_description',
            field=models.TextField(default='bievenu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kalima',
            name='fr_description',
            field=models.TextField(default='welcome'),
            preserve_default=False,
        ),
    ]
