# Generated by Django 4.1 on 2022-09-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0004_kalima_en_description_kalima_fr_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kalima',
            name='ar_description',
            field=models.TextField(default='شرح عربية'),
        ),
        migrations.AlterField(
            model_name='kalima',
            name='en_description',
            field=models.TextField(default='English description'),
        ),
        migrations.AlterField(
            model_name='kalima',
            name='fr_description',
            field=models.TextField(default='Description Française'),
        ),
    ]
